### ISSUE TITLE
Parsing logic for EnvDetector failed to grab CURL information 

### ISSUE THREAD

**Issue by renfeiw** [adoptium/TKG#456]
For example: version prints out: “curl 7.71.1 (powerpc-ibm-aix6.1.9.0) libcurl/7.71.1 OpenSSL/1.0.2u zlib/1.2.11 libssh2/1.8.2 nghttp2/1.41.0” The parser reads 1.0.2 instead of 7.71.1

**Comment by renfeiw** [comment]
After digging more on the issue, found `bash -c "curl --version"` executed by java ProcessBuilder has the following output: 
```
17:24:07  	exec(): 0509-036 Cannot load program curl because of the following errors:
17:24:07  		0509-022 Cannot load module /opt/freeware/lib64/libcurl.a(libcurl.so.4).
17:24:07  		0509-150   Dependent module /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/libcrypto.a(libcrypto.so.1.0.2) could not be loaded.
17:24:07  		0509-152   Member libcrypto.so.1.0.2 is not found in archive 
17:24:07  		0509-022 Cannot load module curl_64.
17:24:07  		0509-150   Dependent module /opt/freeware/lib64/libcurl.a(libcurl.so.4) could not be loaded.
```

The same command  outside of Java environment successfully prints out curl version.

**Comment by renfeiw** [comment]
@AdamBrousseau Do you have any idea?

**Comment by KostasTsiounis** [comment]
In the build that I was trying to test and ended up producing this error, I am bundling OpenSSL 3.0.9. This means that there is a file `jdk/lib/libcrypto.a` which contains only `libcrypto.so.3`.

But existing curl needs `OpenSSL 1.0.2`, so it looks for a `libcrypto.a` file, finds the bundled one first but there is no `libcrypto.so.1.0.2` in that archive. This leads to the output mentioned in https://github.com/adoptium/TKG/issues/456#issuecomment-1622558437. And since the parser finds the first version looking string, `1.0.2` is saved as the `curl` version.

**Comment by AdamBrousseau** [comment]
I believe what is happening, the Test framework is setting JAVA_HOME to the Java under test and when ant executes, it runs using this java instead of the system default java. This is coming from my memory of a past issue that had an environment issue which we tracked back to JAVA_HOME changing which java ant picked up. Ideally we would run ant with system default java.

As a potential solution, we are going to try and install a newer version of curl on one of the (aix) machines where we are seeing this issue. The newer version will be able to run with openssl 3. We are tracking that in an internal issue but will update here with the results.

**Comment by renfeiw** [comment]
Thanks @KostasTsiounis for pointing out the root cause. I have made a change to use parent shell environment from the processbuilder, this could this issue and avoid any error similar to this.
