### ISSUE TITLE
Remove unused 3rd party jars

### ISSUE THREAD

**Issue by llxia** [adoptium/TKG#468]
All 3rd party jars are downloaded via https://github.com/adoptium/TKG/blob/master/scripts/getDependencies.pl
We have a total of 140M now. We should remove the jars that we do not need to use. 

For example, the following jars are no longer used in https://github.com/adoptium/aqa-tests/blob/master/openjdk/build.xml. They should be removed.
- jtreg_6_1_1.tar.gz => for JDK18, 19
- jtreg_7_2_1.tar.gz => not used
- jtreg_7_1_1_1.tar.gz => JDK20
- jtreg_7_3_1.tar.gz => not used

We should also check for other jars.

**Comment by pshipton** [comment]
Due to the limited bandwidth available to some of the OpenJ9 (UNB) machines, the excessive copyArtifacts downloads seem to be saturating the pipe and causing test jobs to fail. It appears jenkins can't contact the machines because the network pipe is saturated. We can't prove it, but if we try to run enough testing on these machines, it seems to take down jenkins itself.

**Comment by llxia** [comment]
@LongyuZhang could you help to remove the unused jars? Thanks

**Comment by llxia** [comment]
related: https://github.com/adoptium/aqa-tests/issues/4500

**Comment by llxia** [comment]
PRs are delivered.
